Parth CHS/Parth CHS/Controllers/DashboardController.cs
using Parth_CHS.DataLayer;
using Parth_CHS.Filters;
using Parth_CHS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Parth_CHS.Controllers
{
    [AccessFilter]
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult DashboardView()
        {
            return View();
        }

        public ActionResult DashboardPaymentView( int Year)
        {

            List<DashboardModel> list = new List<DashboardModel>();
            DashboardDL dashboardDL = new DashboardDL();
            list = dashboardDL.UserDashboardPaymentView((int)Session["UserId"], Year);
            
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdatePayment(int Id)
        {
            DashboardDL dashboardDL = new DashboardDL();
            bool result = dashboardDL.UpdatePayment(Id);

            return Json(result, JsonRequestBehavior.AllowGet);
        }


        public ActionResult NoAccess() 
        {
            return View();
        }
    }
}

Parth CHS/Parth CHS/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Parth_CHS.Filters;
using Parth_CHS.Models;

namespace Parth_CHS.Controllers
{
    [AccessFilter]
    [Permission]
    public class EventsController : Controller
    {
        // GET: Events
        public ActionResult Members()
        {
            List<WomenEvents> objlist = new List<WomenEvents>();
            using (SqlConnection cn = new SqlConnection("server=.; Database= Women ; Trusted_Connection= True;"))
            {
                cn.Open();
                SqlCommand command = new SqlCommand();
                command.Connection = cn;
                command.CommandText = "GetallWomendetails";
                command.CommandType = System.Data.CommandType.StoredProcedure;

                using (SqlDataReader reader = command.ExecuteReader())
                {

                    while (reader.Read())
                    {
                        WomenEvents F = new WomenEvents();
                        F.Id = (int)reader["Id"];
                        F.FirstName = (string)reader["FirstName"];
                        F.MiddleName = (string)reader["MiddleName"];
                        F.LastName = (string)reader["LastName"];
                        F.PhoneNo = (Int64)reader["PhoneNo"];
                        F.AdharNo = (Int64)reader["AdharNo"];
                        F.EmailId = (string)reader["EmailId"];
                        F.RoomNo = (int)reader["RoomNo"];
                        F.FloorNo = (int)reader["FloorNo"];
                        F.Designation = (string)reader["Designation"];


                        objlist.Add(F);

                    }
                    cn.Close();

                }


            }
            return View(objlist);
        }

        public ActionResult GetDesignation()
        {
            List<WomenDesignation> designationList = new List<WomenDesignation>();
            using (SqlConnection connection = new SqlConnection("server = .; Database = Women; Trusted_Connection = True;"))
            {
                SqlCommand cmd = new SqlCommand();
                cmd.Connection = connection;
                cmd.CommandText = "GetallDesignation";
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                connection.Open();
                using (SqlDataReader reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        WomenDesignation data = new WomenDesignation();
                        data.Id = (int)reader["Id"];
                        data.Designation = (string)reader["Designation"];
                        designationList.Add(data);
                    }
                }
                connection.Close();
            }
            return Json(designationList, JsonRequestBehavior.AllowGet);


        }

        public ActionResult GetRoomNos() {
            List<WomenRoomNo> roomNolist = new List<WomenRoomNo>();

            using (SqlConnection connection = new SqlConnection("server = .; Database = Women; Trusted_Connection = True;"))
            {
                SqlCommand cmd = new SqlCommand();
                cmd.Connection = connection;
                cmd.CommandText = "GetallRoom";
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                connection.Open();

                using (SqlDataReader reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        WomenRoomNo data = new WomenRoomNo();
                        data.Id = (int)reader["Id"];
                        data.RoomNo = (int)reader["RoomNo"];
                        data.FloorNo = (int)reader["FloorNo"];
                        roomNolist.Add(data);
                    }
                
                
                }
                connection.Close();




            }
            return Json(roomNolist, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveMembersdetails(WomenEvents data) 
        {
            using (SqlConnection cn = new SqlConnection("server=.; Database= Women; Trusted_Connection = True; "))
            {
                cn.Open();
                SqlCommand command = new SqlCommand();
                command.Connection = cn;
                command.CommandText = "InsertIntoWomen_tbl";
                command.CommandType = System.Data.CommandType.StoredProcedure;

                command.Parameters.AddWithValue("@FirstName", data.FirstName);
                command.Parameters.AddWithValue("@MiddleName", data.MiddleName);
                command.Parameters.AddWithValue("@LastName", data.LastName);
                command.Parameters.AddWithValue("@PhoneNo", data.PhoneNo);
                command.Parameters.AddWithValue("@AdharNo", data.AdharNo);
                command.Parameters.AddWithValue("@EmailId", data.EmailId);
                command.Parameters.AddWithValue("@RoomId", data.RoomsId);
                command.Parameters.AddWithValue("@DesignationId", data.DesignationId);

                command.ExecuteNonQuery();
                cn.Close();

            }

            return Json(true, JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetWomendetailsById(int Id) 
        
        {
            WomenEvents data = new WomenEvents();
            using (SqlConnection cn = new SqlConnection("server = .; Database = Women; Trusted_Connection = True;"))
            {
                cn.Open();
                SqlCommand command = new SqlCommand();
                command.Connection = cn;
                command.CommandText = "GetWomenMemberById";
                command.CommandType = System.Data.CommandType.StoredProcedure;
                command.Parameters.AddWithValue("@Id", Id);

                using (SqlDataReader reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        data.Id = (int)reader["Id"];
                        data.FirstName = (string)reader["FirstName"];
                        data.MiddleName = (string)reader["MiddleName"];
                        data.LastName = (string)reader["LastName"];
                        data.PhoneNo = (Int64)reader["PhoneNo"];
                        data.AdharNo = (Int64)reader["AdharNo"];
                        data.EmailId = (string)reader["EmailId"];
                        data.RoomsId = (int)reader["RoomId"];
                        data.RoomNo = (int)reader["RoomNo"];
                        data.FloorNo = (int)reader["FloorNo"];
                        data.DesignationId = (int)reader["DesignationId"];
                        data.Designation = (string)reader["Designation"];
                       
                        break;
                    }
                }
                cn.Close();

            }
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveEditedMembersdetails(WomenEvents data)
        {
            using (SqlConnection cn = new SqlConnection("server=.; Database= Women; Trusted_Connection = True; "))
            {
                cn.Open();
                SqlCommand command = new SqlCommand();
                command.Connection = cn;
                command.CommandText = "UpdateWomendetails";
                command.CommandType = System.Data.CommandType.StoredProcedure;

                command.Parameters.AddWithValue("@Id", data.Id);
                command.Parameters.AddWithValue("@FirstName", data.FirstName);
                command.Parameters.AddWithValue("@MiddleName", data.MiddleName);
                command.Parameters.AddWithValue("@LastName", data.LastName);
                command.Parameters.AddWithValue("@PhoneNo", data.PhoneNo);
                command.Parameters.AddWithValue("@AdharNo", data.AdharNo);
                command.Parameters.AddWithValue("@EmailId", data.EmailId);
                command.Parameters.AddWithValue("@RoomId", data.RoomsId);
                command.Parameters.AddWithValue("@DesignationId", data.DesignationId);

                command.ExecuteNonQuery();
                cn.Close();

            }

            return Json(true, JsonRequestBehavior.AllowGet);


        }

        public ActionResult DeleteWomendetailsById(int Id) 
        {
            using (SqlConnection cn = new SqlConnection("server = .; Database = Women; Trusted_Connection = True;"))
            {
                cn.Open();
                SqlCommand command = new SqlCommand();
                command.Connection = cn;
                command.CommandText = "DeleteWomenDetails";
                command.CommandType = System.Data.CommandType.StoredProcedure;
                command.Parameters.AddWithValue("@Id", Id);
                command.ExecuteNonQuery();
                cn.Close();
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }

}

Parth CHS/Parth CHS/Controllers/UserProfileController.cs
using Parth_CHS.DataLayer;
using Parth_CHS.Filters;
using Parth_CHS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Parth_CHS.Controllers
{
    public class UserProfileController : Controller
    {
        // GET: UserProfile
        public ActionResult Profile()
        {
            return View();
        }

        public ActionResult GetUserProfileDetails()
        {

            Users data = new Users();
            UserDL userDL = new UserDL();
            data = userDL.GetUserDetailsById((int)Session["UserId"]);


            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveUserProfileEditedDetails(Users data)
        {
            UserDL usersDL = new UserDL();
            bool result = usersDL.UpdateUserDetails(data);


            return Json(result, JsonRequestBehavior.AllowGet);

        }

    }

    
}

Parth CHS/Parth CHS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap-switch-button@1.1.0/css/bootstrap-switch-button.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap-switch-button@1.1.0/dist/bootstrap-switch-button.min.js"></script>

    <script>
        function confirmpopup() {
            $('#LogOutpopup').modal('show');
        }

        function Logout() {
            $.ajax({
                url: "https://localhost:44372/LogIn/LogOut",
                cache: false,
                success: function (data) {

                    alert("Logged Out Successfully ");
                    $('#deletemyModal').modal('hide');
                    window.location.reload();
                },
                error: function (errmessage) {
                    console.log(errmessage);
                }

            });
        }

        function userprofilepage() {
            $.ajax({
                url: "https://localhost:44372/UserProfile/Profile",
                cache: false,
                success: function () {
                },
                error: function (errmessage) {
                    console.log(errmessage);
                }

            });
        }


    </script>


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Parth CHS", "DashboardView", "Dashboard", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if ((int)Session["Designation"] == 1 || (int)Session["Designation"] == 2 || (int)Session["Designation"] == 3)
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Maintenance", "Page", "Maintenance")</li>
                        <li>@Html.ActionLink("Women", "Members", "Events")</li>
                        <li>@Html.ActionLink("Payment", "PaymentView", "Payment")</li>
                    }

                    <li>@Html.ActionLink("Dashboard", "DashboardView", "Dashboard")</li>
                    <li><a href="#" onclick="confirmpopup()">LogOut</a></li>
                    <li>@Html.ActionLink("Profile", "Profile", "UserProfile")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)


    <div class="modal fade" id="LogOutpopup" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h4 class="modal-title">LogOut</h4>
                </div>
                <div class="modal-body">
                    Are you sure, You want to LogOut?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" onclick="Logout()">Yes</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>


</body>
</html>

Parth CHS/Parth CHS/Views/Shared/_LogInLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>